### PR TITLE
Create main.yml

### PR DESCRIPTION
**Pull request by Retr0ve**
Create a GitHub Action to run the build script and deploy it to GitHub page.

### CODE REVIEW

**Comment by PackElend** [comment]
Should it be #5

**Comment by Retr0ve** [comment]
It is generated automatically by GitHub

**Comment by personalizedrefrigerator** [comment]
I haven't tested this, but it looks good to me!

**Comment by PackElend** [comment]
> I haven't tested this (testing [GitHub actions locally seems to require some setup](https://stackoverflow.com/questions/59241249/how-to-run-github-actions-workflows-locally)), but it looks good to me!

@Retr0ve can you say anything?

@personalizedrefrigerator do so any reason not to merge it?

**Comment by Retr0ve** [comment]
This script is tested in my demo repo and it works fine. :)

**Comment by laurent22** [comment]
Thanks for the update @Retr0ve, and thanks for reviewing @personalizedrefrigerator. If it's all good let's merge then.

The next step will be to review the full website and deploy it. I expect however that we'll need to change or remove certain features and add new ones, so the process will take some time but we'll get there eventually.

**Pull request merged**
